Repository AY2021S1-CS2103T-F11-1/tp, pull requests merged in 2020-10, with the labels that each got.

#50 Fix tasks unable to be loaded from save file
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: priority.High, severity.High, type.Task

#57 Setup Codecov
  README.md
Labels: priority.Low, type.Task

#56 Update user guide
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#69 chore: Update app screenshot
  docs/images/Ui.png
Labels: priority.Low, type.Enhancement, type.Task

#65 chore: Update Add command help text
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: severity.Medium, type.Bug, type.Task

#67 feat: Enable assertions for gradle run task
  build.gradle
Labels: priority.Medium, type.Enhancement

#77 Update help window
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High, severity.Medium, type.Task

#80 Add more very defensive programming
  src/main/java/seedu/address/model/attendance/Attendance.java
  src/main/java/seedu/address/storage/JsonAdaptedAttendance.java
Labels: priority.Low, severity.Low, type.Enhancement, type.Task

#81 docs: Update DG with UI styling information
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Enhancement, type.Task

#85 fix: DG/UG TOC not being generated by Kramdown
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, severity.High, type.Bug

#86 Enable assertions for Attendance constructor
  src/main/java/seedu/address/model/attendance/Attendance.java
Labels: priority.Medium, type.Enhancement, type.Task

#87 Add more assertions at Prefix & UserPrefs
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/main/java/seedu/address/model/UserPrefs.java
Labels: priority.High, priority.Medium, type.Task

#89 ci: Add automerge GH action
  .github/workflows/automerge.yml
Labels: automerge, priority.Low, type.Enhancement

#103 Fix unattend bugs
  src/main/java/seedu/address/logic/commands/UnattendCommand.java
  src/test/java/seedu/address/logic/commands/UnattendCommandTest.java
Labels: automerge, priority.High, severity.High, type.Bug
