Repository AY2021S1-CS2103T-F11-1/tp, pull requests merged in 2020-11, with the labels that each got.

#151 Update image at UG: Find command
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
Labels: automerge

#152 Update UG
  docs/UserGuide.md
Labels: automerge

#154 Fix Show Attendance error message
  src/main/java/seedu/address/logic/commands/ShowAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/ShowAttendanceCommandParser.java
Labels: automerge

#167 Update DG for ExportAttendanceCommand
  docs/DeveloperGuide.md
Labels: priority.Low, severity.Low, type.Enhancement

#164 Create PPP Draft
  docs/team/rishi5154.md
Labels: priority.High, severity.High, type.Task

#165 Improve add command error handling
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: priority.Medium, severity.Medium, type.Enhancement

#177 Fix Quick-Start guide URL
  docs/UserGuide.md
Labels: severity.High, type.Bug

#181 Add tests for Tag, Attendance and LogicManager
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/attendance/AttendanceTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: priority.Medium, severity.Medium, type.Task

#187 Add & Update tests to account for new consultation conflict equality
  src/main/java/seedu/address/model/consultation/Consultation.java
  src/test/java/seedu/address/model/consultation/ConsultationTest.java
  src/test/java/seedu/address/model/consultation/UniqueConsultationListTest.java
Labels: priority.High, type.Task

#190 Update portfolio links in AboutUs.md
  docs/AboutUs.md
  docs/team/johndoe.md
Labels: priority.Medium, severity.Low, type.Task

#192 Integrate Codacy code static analysis
  README.md
Labels: priority.Low, type.Enhancement

#200 Fix Attendance panel size
  src/main/resources/view/AttendanceTablePanel.fxml
Labels: severity.Medium, type.Bug

#198 Fix FXML versioning warnings
  src/main/resources/view/AttendanceTablePanel.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/ConsultationListCard.fxml
  src/main/resources/view/ConsultationListPanel.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/test/resources/view/UiPartTest/validFile.fxml
Labels: severity.Low, type.Bug

#202 Fix empty cell background color
  src/main/resources/view/Extensions.css
Labels: severity.Low, type.Bug

#203 Fix messages for listing students
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListCommand.java
Labels: severity.Low, type.Bug

#204 Add minor UG changes to improve readability
  docs/UserGuide.md
Labels: type.Enhancement

#185 Add more UI unit tests
  src/test/java/seedu/address/ui/UiPartTest.java
Labels: priority.Low, type.Task

#88 ci: Add gradle git hooks
  build.gradle
Labels: do not merge, priority.Low, type.Enhancement
